INFO 2025-02-26 09:37:35,337 aes libssl detected, it will be used for encryption
INFO 2025-02-26 09:37:35,797 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 09:37:35,849 aes libssl detected, it will be used for encryption
INFO 2025-02-26 09:38:40,159 aes libssl detected, it will be used for encryption
INFO 2025-02-26 09:38:40,159 aes libssl detected, it will be used for encryption
ERROR 2025-02-26 09:38:40,326 signal Signal handler <promise@0x1054f7390 --> <bound method Celery._autodiscover_tasks of <Celery backend at 0x1054c05c0>>> raised: ModuleNotFoundError("No module named 'backend.backend'")
Traceback (most recent call last):
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/utils/dispatch/signal.py", line 276, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/vine/promises.py", line 161, in __call__
    return self.throw()
           ^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/vine/promises.py", line 158, in __call__
    retval = fun(*final_args, **final_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/app/base.py", line 693, in _autodiscover_tasks
    return self._autodiscover_tasks_from_names(packages, related_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/app/base.py", line 698, in _autodiscover_tasks_from_names
    return self.loader.autodiscover_tasks(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/loaders/base.py", line 220, in autodiscover_tasks
    mod.__name__ for mod in autodiscover_tasks(packages or (),
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/loaders/base.py", line 246, in autodiscover_tasks
    return [find_related_module(pkg, related_name) for pkg in packages]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/loaders/base.py", line 278, in find_related_module
    raise e
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/loaders/base.py", line 270, in find_related_module
    return importlib.import_module(module_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.8/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/pavelborisov/Dev/faridaily_django/backend/api/tasks.py", line 6, in <module>
    from backend.backend.celery_app import app
ModuleNotFoundError: No module named 'backend.backend'
ERROR 2025-02-26 09:38:40,331 signal Signal handler <promise@0x10262b390 --> <bound method Celery._autodiscover_tasks of <Celery backend at 0x1025f45c0>>> raised: ModuleNotFoundError("No module named 'backend.backend'")
Traceback (most recent call last):
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/utils/dispatch/signal.py", line 276, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/vine/promises.py", line 161, in __call__
    return self.throw()
           ^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/vine/promises.py", line 158, in __call__
    retval = fun(*final_args, **final_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/app/base.py", line 693, in _autodiscover_tasks
    return self._autodiscover_tasks_from_names(packages, related_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/app/base.py", line 698, in _autodiscover_tasks_from_names
    return self.loader.autodiscover_tasks(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/loaders/base.py", line 220, in autodiscover_tasks
    mod.__name__ for mod in autodiscover_tasks(packages or (),
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/loaders/base.py", line 246, in autodiscover_tasks
    return [find_related_module(pkg, related_name) for pkg in packages]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/loaders/base.py", line 278, in find_related_module
    raise e
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/loaders/base.py", line 270, in find_related_module
    return importlib.import_module(module_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.8/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/pavelborisov/Dev/faridaily_django/backend/api/tasks.py", line 6, in <module>
    from backend.backend.celery_app import app
ModuleNotFoundError: No module named 'backend.backend'
INFO 2025-02-26 09:38:40,695 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 09:38:40,734 aes libssl detected, it will be used for encryption
INFO 2025-02-26 09:40:11,408 aes libssl detected, it will be used for encryption
INFO 2025-02-26 09:40:11,408 aes libssl detected, it will be used for encryption
ERROR 2025-02-26 09:40:11,568 signal Signal handler <promise@0x104df7390 --> <bound method Celery._autodiscover_tasks of <Celery backend at 0x104dc0350>>> raised: ModuleNotFoundError("No module named 'backend.backend'")
Traceback (most recent call last):
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/utils/dispatch/signal.py", line 276, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/vine/promises.py", line 161, in __call__
    return self.throw()
           ^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/vine/promises.py", line 158, in __call__
    retval = fun(*final_args, **final_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/app/base.py", line 693, in _autodiscover_tasks
    return self._autodiscover_tasks_from_names(packages, related_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/app/base.py", line 698, in _autodiscover_tasks_from_names
    return self.loader.autodiscover_tasks(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/loaders/base.py", line 220, in autodiscover_tasks
    mod.__name__ for mod in autodiscover_tasks(packages or (),
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/loaders/base.py", line 246, in autodiscover_tasks
    return [find_related_module(pkg, related_name) for pkg in packages]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/loaders/base.py", line 278, in find_related_module
    raise e
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/loaders/base.py", line 270, in find_related_module
    return importlib.import_module(module_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.8/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/pavelborisov/Dev/faridaily_django/backend/api/tasks.py", line 6, in <module>
    from backend.backend.celery import app
ModuleNotFoundError: No module named 'backend.backend'
ERROR 2025-02-26 09:40:11,570 signal Signal handler <promise@0x1215f7390 --> <bound method Celery._autodiscover_tasks of <Celery backend at 0x1215c4350>>> raised: ModuleNotFoundError("No module named 'backend.backend'")
Traceback (most recent call last):
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/utils/dispatch/signal.py", line 276, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/vine/promises.py", line 161, in __call__
    return self.throw()
           ^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/vine/promises.py", line 158, in __call__
    retval = fun(*final_args, **final_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/app/base.py", line 693, in _autodiscover_tasks
    return self._autodiscover_tasks_from_names(packages, related_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/app/base.py", line 698, in _autodiscover_tasks_from_names
    return self.loader.autodiscover_tasks(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/loaders/base.py", line 220, in autodiscover_tasks
    mod.__name__ for mod in autodiscover_tasks(packages or (),
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/loaders/base.py", line 246, in autodiscover_tasks
    return [find_related_module(pkg, related_name) for pkg in packages]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/loaders/base.py", line 278, in find_related_module
    raise e
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/loaders/base.py", line 270, in find_related_module
    return importlib.import_module(module_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.8/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/pavelborisov/Dev/faridaily_django/backend/api/tasks.py", line 6, in <module>
    from backend.backend.celery import app
ModuleNotFoundError: No module named 'backend.backend'
INFO 2025-02-26 09:40:11,897 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 09:40:11,939 aes libssl detected, it will be used for encryption
INFO 2025-02-26 09:41:45,346 aes libssl detected, it will be used for encryption
INFO 2025-02-26 09:41:45,347 aes libssl detected, it will be used for encryption
ERROR 2025-02-26 09:41:45,498 signal Signal handler <promise@0x106c0b390 --> <bound method Celery._autodiscover_tasks of <Celery backend at 0x106bd4440>>> raised: ModuleNotFoundError("No module named 'backend.backend'")
Traceback (most recent call last):
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/utils/dispatch/signal.py", line 276, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/vine/promises.py", line 161, in __call__
    return self.throw()
           ^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/vine/promises.py", line 158, in __call__
    retval = fun(*final_args, **final_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/app/base.py", line 693, in _autodiscover_tasks
    return self._autodiscover_tasks_from_names(packages, related_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/app/base.py", line 698, in _autodiscover_tasks_from_names
    return self.loader.autodiscover_tasks(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/loaders/base.py", line 220, in autodiscover_tasks
    mod.__name__ for mod in autodiscover_tasks(packages or (),
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/loaders/base.py", line 246, in autodiscover_tasks
    return [find_related_module(pkg, related_name) for pkg in packages]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/loaders/base.py", line 278, in find_related_module
    raise e
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/loaders/base.py", line 270, in find_related_module
    return importlib.import_module(module_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.8/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/pavelborisov/Dev/faridaily_django/backend/api/tasks.py", line 6, in <module>
    from backend.backend.celery import app
ModuleNotFoundError: No module named 'backend.backend'
ERROR 2025-02-26 09:41:45,502 signal Signal handler <promise@0x102b87390 --> <bound method Celery._autodiscover_tasks of <Celery backend at 0x1020610a0>>> raised: ModuleNotFoundError("No module named 'backend.backend'")
Traceback (most recent call last):
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/utils/dispatch/signal.py", line 276, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/vine/promises.py", line 161, in __call__
    return self.throw()
           ^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/vine/promises.py", line 158, in __call__
    retval = fun(*final_args, **final_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/app/base.py", line 693, in _autodiscover_tasks
    return self._autodiscover_tasks_from_names(packages, related_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/app/base.py", line 698, in _autodiscover_tasks_from_names
    return self.loader.autodiscover_tasks(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/loaders/base.py", line 220, in autodiscover_tasks
    mod.__name__ for mod in autodiscover_tasks(packages or (),
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/loaders/base.py", line 246, in autodiscover_tasks
    return [find_related_module(pkg, related_name) for pkg in packages]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/loaders/base.py", line 278, in find_related_module
    raise e
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/loaders/base.py", line 270, in find_related_module
    return importlib.import_module(module_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.8/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/pavelborisov/Dev/faridaily_django/backend/api/tasks.py", line 6, in <module>
    from backend.backend.celery import app
ModuleNotFoundError: No module named 'backend.backend'
INFO 2025-02-26 09:41:45,810 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 09:41:45,846 aes libssl detected, it will be used for encryption
INFO 2025-02-26 09:43:42,384 aes libssl detected, it will be used for encryption
INFO 2025-02-26 09:43:42,385 aes libssl detected, it will be used for encryption
ERROR 2025-02-26 09:43:42,530 signal Signal handler <promise@0x1058f3390 --> <bound method Celery._autodiscover_tasks of <Celery backend at 0x1058c0410>>> raised: ModuleNotFoundError("No module named 'backend.backend'")
Traceback (most recent call last):
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/utils/dispatch/signal.py", line 276, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/vine/promises.py", line 161, in __call__
    return self.throw()
           ^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/vine/promises.py", line 158, in __call__
    retval = fun(*final_args, **final_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/app/base.py", line 693, in _autodiscover_tasks
    return self._autodiscover_tasks_from_names(packages, related_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/app/base.py", line 698, in _autodiscover_tasks_from_names
    return self.loader.autodiscover_tasks(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/loaders/base.py", line 220, in autodiscover_tasks
    mod.__name__ for mod in autodiscover_tasks(packages or (),
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/loaders/base.py", line 246, in autodiscover_tasks
    return [find_related_module(pkg, related_name) for pkg in packages]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/loaders/base.py", line 278, in find_related_module
    raise e
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/loaders/base.py", line 270, in find_related_module
    return importlib.import_module(module_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.8/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/pavelborisov/Dev/faridaily_django/backend/api/tasks.py", line 6, in <module>
    from backend.backend.celery import app
ModuleNotFoundError: No module named 'backend.backend'
ERROR 2025-02-26 09:43:42,534 signal Signal handler <promise@0x10638b390 --> <bound method Celery._autodiscover_tasks of <Celery backend at 0x1059069f0>>> raised: ModuleNotFoundError("No module named 'backend.backend'")
Traceback (most recent call last):
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/utils/dispatch/signal.py", line 276, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/vine/promises.py", line 161, in __call__
    return self.throw()
           ^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/vine/promises.py", line 158, in __call__
    retval = fun(*final_args, **final_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/app/base.py", line 693, in _autodiscover_tasks
    return self._autodiscover_tasks_from_names(packages, related_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/app/base.py", line 698, in _autodiscover_tasks_from_names
    return self.loader.autodiscover_tasks(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/loaders/base.py", line 220, in autodiscover_tasks
    mod.__name__ for mod in autodiscover_tasks(packages or (),
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/loaders/base.py", line 246, in autodiscover_tasks
    return [find_related_module(pkg, related_name) for pkg in packages]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/loaders/base.py", line 278, in find_related_module
    raise e
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/loaders/base.py", line 270, in find_related_module
    return importlib.import_module(module_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.8/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/pavelborisov/Dev/faridaily_django/backend/api/tasks.py", line 6, in <module>
    from backend.backend.celery import app
ModuleNotFoundError: No module named 'backend.backend'
INFO 2025-02-26 09:43:42,836 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 09:43:42,873 aes libssl detected, it will be used for encryption
ERROR 2025-02-26 09:43:47,335 exception Invalid HTTP_HOST header: 'localhost:8020'. You may need to add 'localhost' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:8020'. You may need to add 'localhost' to ALLOWED_HOSTS.
WARNING 2025-02-26 09:43:47,359 log Bad Request: /api/auth/verify
ERROR 2025-02-26 09:44:04,383 exception Invalid HTTP_HOST header: 'localhost:8020'. You may need to add 'localhost' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:8020'. You may need to add 'localhost' to ALLOWED_HOSTS.
WARNING 2025-02-26 09:44:04,398 log Bad Request: /api/auth/verify
ERROR 2025-02-26 09:44:04,400 exception Invalid HTTP_HOST header: 'localhost:8020'. You may need to add 'localhost' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:8020'. You may need to add 'localhost' to ALLOWED_HOSTS.
WARNING 2025-02-26 09:44:04,412 log Bad Request: /api/auth/verify
ERROR 2025-02-26 09:44:09,437 exception Invalid HTTP_HOST header: 'localhost:8020'. You may need to add 'localhost' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:8020'. You may need to add 'localhost' to ALLOWED_HOSTS.
WARNING 2025-02-26 09:44:09,446 log Bad Request: /api/token/pair
INFO 2025-02-26 09:44:55,411 aes libssl detected, it will be used for encryption
INFO 2025-02-26 09:44:55,413 aes libssl detected, it will be used for encryption
ERROR 2025-02-26 09:44:55,624 signal Signal handler <promise@0x1061eb390 --> <bound method Celery._autodiscover_tasks of <Celery backend at 0x1061b8800>>> raised: ModuleNotFoundError("No module named 'backend.backend'")
Traceback (most recent call last):
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/utils/dispatch/signal.py", line 276, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/vine/promises.py", line 161, in __call__
    return self.throw()
           ^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/vine/promises.py", line 158, in __call__
    retval = fun(*final_args, **final_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/app/base.py", line 693, in _autodiscover_tasks
    return self._autodiscover_tasks_from_names(packages, related_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/app/base.py", line 698, in _autodiscover_tasks_from_names
    return self.loader.autodiscover_tasks(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/loaders/base.py", line 220, in autodiscover_tasks
    mod.__name__ for mod in autodiscover_tasks(packages or (),
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/loaders/base.py", line 246, in autodiscover_tasks
    return [find_related_module(pkg, related_name) for pkg in packages]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/loaders/base.py", line 278, in find_related_module
    raise e
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/loaders/base.py", line 270, in find_related_module
    return importlib.import_module(module_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.8/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/pavelborisov/Dev/faridaily_django/backend/api/tasks.py", line 6, in <module>
    from backend.backend.celery import app
ModuleNotFoundError: No module named 'backend.backend'
ERROR 2025-02-26 09:44:55,628 signal Signal handler <promise@0x1065c3390 --> <bound method Celery._autodiscover_tasks of <Celery backend at 0x10658c7d0>>> raised: ModuleNotFoundError("No module named 'backend.backend'")
Traceback (most recent call last):
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/utils/dispatch/signal.py", line 276, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/vine/promises.py", line 161, in __call__
    return self.throw()
           ^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/vine/promises.py", line 158, in __call__
    retval = fun(*final_args, **final_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/app/base.py", line 693, in _autodiscover_tasks
    return self._autodiscover_tasks_from_names(packages, related_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/app/base.py", line 698, in _autodiscover_tasks_from_names
    return self.loader.autodiscover_tasks(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/loaders/base.py", line 220, in autodiscover_tasks
    mod.__name__ for mod in autodiscover_tasks(packages or (),
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/loaders/base.py", line 246, in autodiscover_tasks
    return [find_related_module(pkg, related_name) for pkg in packages]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/loaders/base.py", line 278, in find_related_module
    raise e
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/loaders/base.py", line 270, in find_related_module
    return importlib.import_module(module_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.8/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/pavelborisov/Dev/faridaily_django/backend/api/tasks.py", line 6, in <module>
    from backend.backend.celery import app
ModuleNotFoundError: No module named 'backend.backend'
INFO 2025-02-26 09:44:56,054 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 09:44:56,093 aes libssl detected, it will be used for encryption
INFO 2025-02-26 09:45:03,248 operation "POST - AsyncNinjaJWTSlidingController[obtain_token] /api/token/pair" 0.30093812942504883
INFO 2025-02-26 09:45:03,265 operation "GET - AuthController[verify] /api/auth/verify" 0.0013358592987060547
INFO 2025-02-26 09:45:03,269 operation "GET - AuthController[verify] /api/auth/verify" 0.002293109893798828
INFO 2025-02-26 09:45:03,312 mtprotosender Connecting to 149.154.167.92:443/TcpFull...
INFO 2025-02-26 09:45:03,313 operation "GET - DraftController[get_drafts] /api/drafts/" 0.007798194885253906
INFO 2025-02-26 09:45:03,318 operation "GET - DraftController[get_drafts] /api/drafts/" 0.0031881332397460938
INFO 2025-02-26 09:45:03,337 operation "GET - TelegramController[get_channel_data] /api/tg/get_channel_data" 0.03280997276306152
INFO 2025-02-26 09:45:03,371 operation "GET - TelegramController[get_messages] /api/tg/messages" 0.06782293319702148
INFO 2025-02-26 09:45:03,381 mtprotosender Connection to 149.154.167.92:443/TcpFull complete!
INFO 2025-02-26 09:45:03,383 operation "GET - TelegramController[get_channel_data] /api/tg/get_channel_data" 0.04362988471984863
INFO 2025-02-26 09:45:03,467 operation "GET - TelegramController[get_messages] /api/tg/messages" 0.092376708984375
INFO 2025-02-26 09:45:04,492 mtprotosender Disconnecting from 149.154.167.92:443/TcpFull...
INFO 2025-02-26 09:45:04,493 mtprotosender Disconnection from 149.154.167.92:443/TcpFull complete!
INFO 2025-02-26 09:45:04,524 operation "GET - TelegramController[refresh_data] /api/tg/refresh_data" 1.2169930934906006
INFO 2025-02-26 09:45:04,527 mtprotosender Connecting to 149.154.167.92:443/TcpFull...
INFO 2025-02-26 09:45:04,557 mtprotosender Connection to 149.154.167.92:443/TcpFull complete!
INFO 2025-02-26 09:45:07,889 mtprotosender Disconnecting from 149.154.167.92:443/TcpFull...
INFO 2025-02-26 09:45:07,889 mtprotosender Disconnection from 149.154.167.92:443/TcpFull complete!
INFO 2025-02-26 09:45:07,916 operation "GET - TelegramController[refresh_data] /api/tg/refresh_data" 3.3907978534698486
INFO 2025-02-26 09:45:11,916 operation "GET - AuthController[verify] /api/auth/verify" 0.003381013870239258
INFO 2025-02-26 09:45:11,927 operation "GET - AuthController[verify] /api/auth/verify" 0.008813858032226562
INFO 2025-02-26 09:45:11,935 operation "GET - AuthController[verify] /api/auth/verify" 0.003616809844970703
INFO 2025-02-26 09:45:11,943 operation "GET - AuthController[verify] /api/auth/verify" 0.004591226577758789
INFO 2025-02-26 09:45:11,979 operation "GET - DraftController[get_drafts] /api/drafts/" 0.010436773300170898
INFO 2025-02-26 09:45:11,982 mtprotosender Connecting to 149.154.167.92:443/TcpFull...
INFO 2025-02-26 09:45:11,986 operation "GET - TelegramController[get_channel_data] /api/tg/get_channel_data" 0.014064788818359375
INFO 2025-02-26 09:45:11,995 operation "GET - DraftController[get_drafts] /api/drafts/" 0.011034011840820312
INFO 2025-02-26 09:45:12,000 operation "GET - TelegramController[get_channel_data] /api/tg/get_channel_data" 0.012064933776855469
INFO 2025-02-26 09:45:12,021 mtprotosender Connection to 149.154.167.92:443/TcpFull complete!
INFO 2025-02-26 09:45:12,071 operation "GET - TelegramController[get_messages] /api/tg/messages" 0.10075592994689941
INFO 2025-02-26 09:45:12,224 operation "GET - TelegramController[get_messages] /api/tg/messages" 0.15075922012329102
INFO 2025-02-26 09:45:13,531 mtprotosender Disconnecting from 149.154.167.92:443/TcpFull...
INFO 2025-02-26 09:45:13,531 mtprotosender Disconnection from 149.154.167.92:443/TcpFull complete!
INFO 2025-02-26 09:45:13,567 operation "GET - TelegramController[refresh_data] /api/tg/refresh_data" 1.5934422016143799
INFO 2025-02-26 09:45:13,571 mtprotosender Connecting to 149.154.167.92:443/TcpFull...
INFO 2025-02-26 09:45:13,645 mtprotosender Connection to 149.154.167.92:443/TcpFull complete!
INFO 2025-02-26 09:45:14,692 mtprotosender Disconnecting from 149.154.167.92:443/TcpFull...
INFO 2025-02-26 09:45:14,692 mtprotosender Disconnection from 149.154.167.92:443/TcpFull complete!
INFO 2025-02-26 09:45:14,733 operation "GET - TelegramController[refresh_data] /api/tg/refresh_data" 1.164315938949585
INFO 2025-02-26 09:45:51,619 aes libssl detected, it will be used for encryption
INFO 2025-02-26 09:45:51,620 aes libssl detected, it will be used for encryption
INFO 2025-02-26 09:45:52,646 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 09:45:52,705 aes libssl detected, it will be used for encryption
INFO 2025-02-26 09:45:57,946 operation "GET - AuthController[verify] /api/auth/verify" 0.04196906089782715
INFO 2025-02-26 09:45:57,952 operation "GET - AuthController[verify] /api/auth/verify" 0.004858970642089844
INFO 2025-02-26 09:45:57,958 operation "GET - AuthController[verify] /api/auth/verify" 0.002588033676147461
INFO 2025-02-26 09:45:57,962 operation "GET - AuthController[verify] /api/auth/verify" 0.002454042434692383
INFO 2025-02-26 09:45:57,990 operation "GET - DraftController[get_drafts] /api/drafts/" 0.007471799850463867
INFO 2025-02-26 09:45:57,990 mtprotosender Connecting to 149.154.167.92:443/TcpFull...
INFO 2025-02-26 09:45:57,995 operation "GET - DraftController[get_drafts] /api/drafts/" 0.002946138381958008
INFO 2025-02-26 09:45:58,012 operation "GET - TelegramController[get_channel_data] /api/tg/get_channel_data" 0.027813196182250977
INFO 2025-02-26 09:45:58,044 operation "GET - TelegramController[get_messages] /api/tg/messages" 0.06094717979431152
INFO 2025-02-26 09:45:58,057 mtprotosender Connection to 149.154.167.92:443/TcpFull complete!
INFO 2025-02-26 09:45:58,077 operation "GET - TelegramController[get_channel_data] /api/tg/get_channel_data" 0.06347489356994629
INFO 2025-02-26 09:45:58,146 operation "GET - TelegramController[get_messages] /api/tg/messages" 0.08435916900634766
INFO 2025-02-26 09:45:59,432 mtprotosender Disconnecting from 149.154.167.92:443/TcpFull...
INFO 2025-02-26 09:45:59,433 mtprotosender Disconnection from 149.154.167.92:443/TcpFull complete!
INFO 2025-02-26 09:45:59,479 operation "GET - TelegramController[refresh_data] /api/tg/refresh_data" 1.494621992111206
INFO 2025-02-26 09:45:59,482 mtprotosender Connecting to 149.154.167.92:443/TcpFull...
INFO 2025-02-26 09:45:59,522 mtprotosender Connection to 149.154.167.92:443/TcpFull complete!
INFO 2025-02-26 09:46:00,291 mtprotosender Disconnecting from 149.154.167.92:443/TcpFull...
INFO 2025-02-26 09:46:00,291 mtprotosender Disconnection from 149.154.167.92:443/TcpFull complete!
INFO 2025-02-26 09:46:00,337 operation "GET - TelegramController[refresh_data] /api/tg/refresh_data" 0.8563220500946045
INFO 2025-02-26 09:47:33,861 aes libssl detected, it will be used for encryption
INFO 2025-02-26 09:47:33,862 aes libssl detected, it will be used for encryption
ERROR 2025-02-26 09:47:34,003 signal Signal handler <promise@0x106f57390 --> <bound method Celery._autodiscover_tasks of <Celery backend at 0x106f246e0>>> raised: ModuleNotFoundError("No module named 'backend.celery'")
Traceback (most recent call last):
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/utils/dispatch/signal.py", line 276, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/vine/promises.py", line 161, in __call__
    return self.throw()
           ^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/vine/promises.py", line 158, in __call__
    retval = fun(*final_args, **final_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/app/base.py", line 693, in _autodiscover_tasks
    return self._autodiscover_tasks_from_names(packages, related_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/app/base.py", line 698, in _autodiscover_tasks_from_names
    return self.loader.autodiscover_tasks(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/loaders/base.py", line 220, in autodiscover_tasks
    mod.__name__ for mod in autodiscover_tasks(packages or (),
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/loaders/base.py", line 246, in autodiscover_tasks
    return [find_related_module(pkg, related_name) for pkg in packages]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/loaders/base.py", line 278, in find_related_module
    raise e
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/loaders/base.py", line 270, in find_related_module
    return importlib.import_module(module_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.8/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/pavelborisov/Dev/faridaily_django/backend/api/tasks.py", line 6, in <module>
    from backend.celery import app
ModuleNotFoundError: No module named 'backend.celery'
ERROR 2025-02-26 09:47:34,006 signal Signal handler <promise@0x106ad3390 --> <bound method Celery._autodiscover_tasks of <Celery backend at 0x106a38290>>> raised: ModuleNotFoundError("No module named 'backend.celery'")
Traceback (most recent call last):
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/utils/dispatch/signal.py", line 276, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/vine/promises.py", line 161, in __call__
    return self.throw()
           ^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/vine/promises.py", line 158, in __call__
    retval = fun(*final_args, **final_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/app/base.py", line 693, in _autodiscover_tasks
    return self._autodiscover_tasks_from_names(packages, related_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/app/base.py", line 698, in _autodiscover_tasks_from_names
    return self.loader.autodiscover_tasks(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/loaders/base.py", line 220, in autodiscover_tasks
    mod.__name__ for mod in autodiscover_tasks(packages or (),
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/loaders/base.py", line 246, in autodiscover_tasks
    return [find_related_module(pkg, related_name) for pkg in packages]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/loaders/base.py", line 278, in find_related_module
    raise e
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/celery/loaders/base.py", line 270, in find_related_module
    return importlib.import_module(module_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.8/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/pavelborisov/Dev/faridaily_django/backend/api/tasks.py", line 6, in <module>
    from backend.celery import app
ModuleNotFoundError: No module named 'backend.celery'
INFO 2025-02-26 09:47:34,310 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 09:47:34,347 aes libssl detected, it will be used for encryption
INFO 2025-02-26 09:47:35,181 operation "GET - AuthController[verify] /api/auth/verify" 0.0352330207824707
INFO 2025-02-26 09:47:35,186 operation "GET - AuthController[verify] /api/auth/verify" 0.0033621788024902344
INFO 2025-02-26 09:47:35,190 operation "GET - AuthController[verify] /api/auth/verify" 0.002167224884033203
INFO 2025-02-26 09:47:35,193 operation "GET - AuthController[verify] /api/auth/verify" 0.0017600059509277344
INFO 2025-02-26 09:47:35,221 operation "GET - DraftController[get_drafts] /api/drafts/" 0.00890493392944336
INFO 2025-02-26 09:47:35,224 mtprotosender Connecting to 149.154.167.92:443/TcpFull...
INFO 2025-02-26 09:47:35,226 operation "GET - DraftController[get_drafts] /api/drafts/" 0.003056049346923828
INFO 2025-02-26 09:47:35,244 operation "GET - TelegramController[get_channel_data] /api/tg/get_channel_data" 0.029449939727783203
INFO 2025-02-26 09:47:35,273 mtprotosender Connection to 149.154.167.92:443/TcpFull complete!
INFO 2025-02-26 09:47:35,272 operation "GET - TelegramController[get_messages] /api/tg/messages" 0.05940699577331543
INFO 2025-02-26 09:47:35,292 operation "GET - TelegramController[get_channel_data] /api/tg/get_channel_data" 0.04641008377075195
INFO 2025-02-26 09:47:35,341 operation "GET - TelegramController[get_messages] /api/tg/messages" 0.06460285186767578
INFO 2025-02-26 09:47:36,266 mtprotosender Disconnecting from 149.154.167.92:443/TcpFull...
INFO 2025-02-26 09:47:36,267 mtprotosender Disconnection from 149.154.167.92:443/TcpFull complete!
INFO 2025-02-26 09:47:36,303 operation "GET - TelegramController[refresh_data] /api/tg/refresh_data" 1.0867009162902832
INFO 2025-02-26 09:47:36,305 mtprotosender Connecting to 149.154.167.92:443/TcpFull...
INFO 2025-02-26 09:47:36,331 mtprotosender Connection to 149.154.167.92:443/TcpFull complete!
INFO 2025-02-26 09:47:37,198 mtprotosender Disconnecting from 149.154.167.92:443/TcpFull...
INFO 2025-02-26 09:47:37,198 mtprotosender Disconnection from 149.154.167.92:443/TcpFull complete!
INFO 2025-02-26 09:47:37,227 operation "GET - TelegramController[refresh_data] /api/tg/refresh_data" 0.9235599040985107
INFO 2025-02-26 09:48:03,585 aes libssl detected, it will be used for encryption
INFO 2025-02-26 09:48:03,586 aes libssl detected, it will be used for encryption
INFO 2025-02-26 09:48:04,200 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 09:48:04,265 aes libssl detected, it will be used for encryption
INFO 2025-02-26 09:48:04,599 operation "GET - AuthController[verify] /api/auth/verify" 0.040932655334472656
INFO 2025-02-26 09:48:04,603 operation "GET - AuthController[verify] /api/auth/verify" 0.0034360885620117188
INFO 2025-02-26 09:48:04,632 operation "GET - DraftController[get_drafts] /api/drafts/" 0.006383180618286133
INFO 2025-02-26 09:48:04,634 mtprotosender Connecting to 149.154.167.92:443/TcpFull...
INFO 2025-02-26 09:48:04,638 operation "GET - DraftController[get_drafts] /api/drafts/" 0.003326892852783203
INFO 2025-02-26 09:48:04,657 operation "GET - TelegramController[get_channel_data] /api/tg/get_channel_data" 0.029102087020874023
INFO 2025-02-26 09:48:04,686 mtprotosender Connection to 149.154.167.92:443/TcpFull complete!
INFO 2025-02-26 09:48:04,685 operation "GET - TelegramController[get_messages] /api/tg/messages" 0.057791948318481445
INFO 2025-02-26 09:48:04,706 operation "GET - TelegramController[get_channel_data] /api/tg/get_channel_data" 0.04827117919921875
INFO 2025-02-26 09:48:04,756 operation "GET - TelegramController[get_messages] /api/tg/messages" 0.05592775344848633
INFO 2025-02-26 09:48:06,151 mtprotosender Disconnecting from 149.154.167.92:443/TcpFull...
INFO 2025-02-26 09:48:06,151 mtprotosender Disconnection from 149.154.167.92:443/TcpFull complete!
INFO 2025-02-26 09:48:06,180 operation "GET - TelegramController[refresh_data] /api/tg/refresh_data" 1.5518481731414795
INFO 2025-02-26 09:48:06,183 mtprotosender Connecting to 149.154.167.92:443/TcpFull...
INFO 2025-02-26 09:48:06,215 mtprotosender Connection to 149.154.167.92:443/TcpFull complete!
INFO 2025-02-26 09:48:07,039 mtprotosender Disconnecting from 149.154.167.92:443/TcpFull...
INFO 2025-02-26 09:48:07,039 mtprotosender Disconnection from 149.154.167.92:443/TcpFull complete!
INFO 2025-02-26 09:48:07,066 operation "GET - TelegramController[refresh_data] /api/tg/refresh_data" 0.8844521045684814
INFO 2025-02-26 19:31:09,416 aes libssl detected, it will be used for encryption
INFO 2025-02-26 19:31:09,416 aes libssl detected, it will be used for encryption
INFO 2025-02-26 19:31:09,898 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 19:31:09,951 aes libssl detected, it will be used for encryption
INFO 2025-02-26 19:31:47,307 operation "GET - AuthController[verify] /api/auth/verify" 0.08018088340759277
WARNING 2025-02-26 19:31:47,308 log Unauthorized: /api/auth/verify
INFO 2025-02-26 19:31:47,309 operation "GET - AuthController[verify] /api/auth/verify" 0.00019812583923339844
WARNING 2025-02-26 19:31:47,309 log Unauthorized: /api/auth/verify
INFO 2025-02-26 19:31:47,314 operation "POST - AsyncNinjaJWTSlidingController[refresh_token] /api/token/refresh" 0.0021240711212158203
INFO 2025-02-26 19:31:47,322 operation "POST - AsyncNinjaJWTSlidingController[refresh_token] /api/token/refresh" 0.005084037780761719
INFO 2025-02-26 19:31:47,325 operation "GET - AuthController[verify] /api/auth/verify" 0.005458354949951172
INFO 2025-02-26 19:31:47,332 operation "GET - AuthController[verify] /api/auth/verify" 0.0015680789947509766
INFO 2025-02-26 19:31:47,393 operation "GET - DraftController[get_drafts] /api/drafts/" 0.014679193496704102
INFO 2025-02-26 19:31:47,400 mtprotosender Connecting to 149.154.167.92:443/TcpFull...
INFO 2025-02-26 19:31:47,403 operation "GET - DraftController[get_drafts] /api/drafts/" 0.0038912296295166016
INFO 2025-02-26 19:31:47,427 operation "GET - TelegramController[get_channel_data] /api/tg/get_channel_data" 0.051976919174194336
INFO 2025-02-26 19:31:47,448 mtprotosender Connection to 149.154.167.92:443/TcpFull complete!
INFO 2025-02-26 19:31:47,454 operation "GET - TelegramController[get_messages] /api/tg/messages" 0.0795440673828125
INFO 2025-02-26 19:31:47,467 operation "GET - TelegramController[get_channel_data] /api/tg/get_channel_data" 0.03841996192932129
INFO 2025-02-26 19:31:47,516 operation "GET - TelegramController[get_messages] /api/tg/messages" 0.0567319393157959
WARNING 2025-02-26 19:31:52,632 operation "GET - TelegramController[refresh_data] /api/tg/refresh_data" ('database is locked',)
ERROR 2025-02-26 19:31:52,633 errors database is locked
Traceback (most recent call last):
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/ninja_extra/operation.py", line 210, in run
    result = self.view_func(request, **values)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/ninja_extra/controllers/route/route_functions.py", line 97, in as_view
    result = self.route.view_func(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/backend/api/controllers/telegram.py", line 112, in refresh_data
    channel_db = fetch_telegram_data(settings.CHANNEL_NAME, MESSAGES_LIMIT)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/backend/api/controllers/telegram.py", line 54, in fetch_telegram_data
    channel_response, messages = asyncio.run(
                                 ^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.8/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.8/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.8/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 686, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/backend/api/telegram/bot.py", line 73, in get_data
    await client.start()
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/telethon/client/auth.py", line 135, in _start
    await self.connect()
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/telethon/client/telegrambaseclient.py", line 559, in connect
    self.session.auth_key = self._sender.auth_key
    ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/telethon/sessions/sqlite.py", line 180, in auth_key
    self._update_session_table()
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/telethon/sessions/sqlite.py", line 194, in _update_session_table
    c.execute('delete from sessions')
sqlite3.OperationalError: database is locked
ERROR 2025-02-26 19:31:52,643 log Internal Server Error: /api/tg/refresh_data
INFO 2025-02-26 19:31:52,650 mtprotosender Connecting to 149.154.167.92:443/TcpFull...
INFO 2025-02-26 19:31:52,676 mtprotosender Connection to 149.154.167.92:443/TcpFull complete!
WARNING 2025-02-26 19:31:57,881 operation "GET - TelegramController[refresh_data] /api/tg/refresh_data" ('database is locked',)
ERROR 2025-02-26 19:31:57,883 errors database is locked
Traceback (most recent call last):
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/ninja_extra/operation.py", line 210, in run
    result = self.view_func(request, **values)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/ninja_extra/controllers/route/route_functions.py", line 97, in as_view
    result = self.route.view_func(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/backend/api/controllers/telegram.py", line 112, in refresh_data
    channel_db = fetch_telegram_data(settings.CHANNEL_NAME, MESSAGES_LIMIT)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/backend/api/controllers/telegram.py", line 54, in fetch_telegram_data
    channel_response, messages = asyncio.run(
                                 ^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.8/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.8/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.8/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 686, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/backend/api/telegram/bot.py", line 73, in get_data
    await client.start()
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/telethon/client/auth.py", line 135, in _start
    await self.connect()
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/telethon/client/telegrambaseclient.py", line 559, in connect
    self.session.auth_key = self._sender.auth_key
    ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/telethon/sessions/sqlite.py", line 180, in auth_key
    self._update_session_table()
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/telethon/sessions/sqlite.py", line 194, in _update_session_table
    c.execute('delete from sessions')
sqlite3.OperationalError: database is locked
ERROR 2025-02-26 19:31:57,888 log Internal Server Error: /api/tg/refresh_data
INFO 2025-02-26 19:32:30,120 operation "GET - AuthController[verify] /api/auth/verify" 0.024888992309570312
INFO 2025-02-26 19:32:30,169 operation "GET - AuthController[verify] /api/auth/verify" 0.0429842472076416
INFO 2025-02-26 19:32:30,215 operation "GET - DraftController[get_drafts] /api/drafts/" 0.019655942916870117
INFO 2025-02-26 19:32:30,221 mtprotosender Connecting to 149.154.167.92:443/TcpFull...
INFO 2025-02-26 19:32:30,226 operation "GET - DraftController[get_drafts] /api/drafts/" 0.007509946823120117
INFO 2025-02-26 19:32:30,245 operation "GET - TelegramController[get_channel_data] /api/tg/get_channel_data" 0.048126935958862305
INFO 2025-02-26 19:32:30,262 mtprotosender Connection to 149.154.167.92:443/TcpFull complete!
INFO 2025-02-26 19:32:30,271 operation "GET - TelegramController[get_channel_data] /api/tg/get_channel_data" 0.023852109909057617
INFO 2025-02-26 19:32:30,370 operation "GET - TelegramController[get_messages] /api/tg/messages" 0.17873811721801758
INFO 2025-02-26 19:32:30,609 operation "GET - TelegramController[get_messages] /api/tg/messages" 0.2335829734802246
INFO 2025-02-26 19:32:33,780 mtprotosender Connecting to 149.154.167.92:443/TcpFull...
INFO 2025-02-26 19:32:33,833 mtprotosender Connection to 149.154.167.92:443/TcpFull complete!
INFO 2025-02-26 19:32:34,076 operation "GET - AuthController[verify] /api/auth/verify" 0.002566099166870117
INFO 2025-02-26 19:32:34,082 operation "GET - AuthController[verify] /api/auth/verify" 0.002988100051879883
INFO 2025-02-26 19:32:34,168 operation "GET - DraftController[get_drafts] /api/drafts/" 0.015658140182495117
INFO 2025-02-26 19:32:34,170 mtprotosender Connecting to 149.154.167.92:443/TcpFull...
INFO 2025-02-26 19:32:34,179 operation "GET - DraftController[get_drafts] /api/drafts/" 0.00494694709777832
INFO 2025-02-26 19:32:34,182 operation "GET - TelegramController[get_channel_data] /api/tg/get_channel_data" 0.023651123046875
INFO 2025-02-26 19:32:34,195 operation "GET - TelegramController[get_channel_data] /api/tg/get_channel_data" 0.011293888092041016
INFO 2025-02-26 19:32:34,213 mtprotosender Connection to 149.154.167.92:443/TcpFull complete!
INFO 2025-02-26 19:32:34,294 operation "GET - TelegramController[get_messages] /api/tg/messages" 0.13990092277526855
INFO 2025-02-26 19:32:34,468 operation "GET - TelegramController[get_messages] /api/tg/messages" 0.16702890396118164
WARNING 2025-02-26 19:32:35,465 operation "GET - TelegramController[refresh_data] /api/tg/refresh_data" ('database is locked',)
ERROR 2025-02-26 19:32:35,465 errors database is locked
Traceback (most recent call last):
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/ninja_extra/operation.py", line 210, in run
    result = self.view_func(request, **values)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/ninja_extra/controllers/route/route_functions.py", line 97, in as_view
    result = self.route.view_func(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/backend/api/controllers/telegram.py", line 112, in refresh_data
    channel_db = fetch_telegram_data(settings.CHANNEL_NAME, MESSAGES_LIMIT)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/backend/api/controllers/telegram.py", line 54, in fetch_telegram_data
    channel_response, messages = asyncio.run(
                                 ^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.8/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.8/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.8/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 686, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/backend/api/telegram/bot.py", line 73, in get_data
    await client.start()
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/telethon/client/auth.py", line 135, in _start
    await self.connect()
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/telethon/client/telegrambaseclient.py", line 559, in connect
    self.session.auth_key = self._sender.auth_key
    ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/telethon/sessions/sqlite.py", line 180, in auth_key
    self._update_session_table()
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/telethon/sessions/sqlite.py", line 194, in _update_session_table
    c.execute('delete from sessions')
sqlite3.OperationalError: database is locked
ERROR 2025-02-26 19:32:35,466 log Internal Server Error: /api/tg/refresh_data
WARNING 2025-02-26 19:32:39,000 operation "GET - TelegramController[refresh_data] /api/tg/refresh_data" ('database is locked',)
ERROR 2025-02-26 19:32:39,004 errors database is locked
Traceback (most recent call last):
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/ninja_extra/operation.py", line 210, in run
    result = self.view_func(request, **values)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/ninja_extra/controllers/route/route_functions.py", line 97, in as_view
    result = self.route.view_func(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/backend/api/controllers/telegram.py", line 112, in refresh_data
    channel_db = fetch_telegram_data(settings.CHANNEL_NAME, MESSAGES_LIMIT)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/backend/api/controllers/telegram.py", line 54, in fetch_telegram_data
    channel_response, messages = asyncio.run(
                                 ^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.8/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.8/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.8/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 686, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/backend/api/telegram/bot.py", line 73, in get_data
    await client.start()
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/telethon/client/auth.py", line 135, in _start
    await self.connect()
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/telethon/client/telegrambaseclient.py", line 559, in connect
    self.session.auth_key = self._sender.auth_key
    ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/telethon/sessions/sqlite.py", line 180, in auth_key
    self._update_session_table()
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/telethon/sessions/sqlite.py", line 194, in _update_session_table
    c.execute('delete from sessions')
sqlite3.OperationalError: database is locked
ERROR 2025-02-26 19:32:39,006 log Internal Server Error: /api/tg/refresh_data
WARNING 2025-02-26 19:32:39,402 operation "GET - TelegramController[refresh_data] /api/tg/refresh_data" ('database is locked',)
ERROR 2025-02-26 19:32:39,403 errors database is locked
Traceback (most recent call last):
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/ninja_extra/operation.py", line 210, in run
    result = self.view_func(request, **values)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/ninja_extra/controllers/route/route_functions.py", line 97, in as_view
    result = self.route.view_func(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/backend/api/controllers/telegram.py", line 112, in refresh_data
    channel_db = fetch_telegram_data(settings.CHANNEL_NAME, MESSAGES_LIMIT)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/backend/api/controllers/telegram.py", line 54, in fetch_telegram_data
    channel_response, messages = asyncio.run(
                                 ^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.8/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.8/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.8/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 686, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/backend/api/telegram/bot.py", line 73, in get_data
    await client.start()
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/telethon/client/auth.py", line 135, in _start
    await self.connect()
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/telethon/client/telegrambaseclient.py", line 559, in connect
    self.session.auth_key = self._sender.auth_key
    ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/telethon/sessions/sqlite.py", line 180, in auth_key
    self._update_session_table()
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/telethon/sessions/sqlite.py", line 194, in _update_session_table
    c.execute('delete from sessions')
sqlite3.OperationalError: database is locked
ERROR 2025-02-26 19:32:39,406 log Internal Server Error: /api/tg/refresh_data
INFO 2025-02-26 19:32:39,423 mtprotosender Connecting to 149.154.167.92:443/TcpFull...
INFO 2025-02-26 19:32:39,450 mtprotosender Connection to 149.154.167.92:443/TcpFull complete!
WARNING 2025-02-26 19:32:44,641 operation "GET - TelegramController[refresh_data] /api/tg/refresh_data" ('database is locked',)
ERROR 2025-02-26 19:32:44,642 errors database is locked
Traceback (most recent call last):
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/ninja_extra/operation.py", line 210, in run
    result = self.view_func(request, **values)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/ninja_extra/controllers/route/route_functions.py", line 97, in as_view
    result = self.route.view_func(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/backend/api/controllers/telegram.py", line 112, in refresh_data
    channel_db = fetch_telegram_data(settings.CHANNEL_NAME, MESSAGES_LIMIT)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/backend/api/controllers/telegram.py", line 54, in fetch_telegram_data
    channel_response, messages = asyncio.run(
                                 ^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.8/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.8/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.8/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 686, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/backend/api/telegram/bot.py", line 73, in get_data
    await client.start()
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/telethon/client/auth.py", line 135, in _start
    await self.connect()
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/telethon/client/telegrambaseclient.py", line 559, in connect
    self.session.auth_key = self._sender.auth_key
    ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/telethon/sessions/sqlite.py", line 180, in auth_key
    self._update_session_table()
  File "/Users/pavelborisov/Dev/faridaily_django/.venv/lib/python3.12/site-packages/telethon/sessions/sqlite.py", line 194, in _update_session_table
    c.execute('delete from sessions')
sqlite3.OperationalError: database is locked
ERROR 2025-02-26 19:32:44,648 log Internal Server Error: /api/tg/refresh_data
INFO 2025-02-26 19:33:58,296 aes libssl detected, it will be used for encryption
INFO 2025-02-26 19:33:58,296 aes libssl detected, it will be used for encryption
INFO 2025-02-26 19:33:58,861 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 19:33:58,949 aes libssl detected, it will be used for encryption
INFO 2025-02-26 19:34:00,867 operation "GET - AuthController[verify] /api/auth/verify" 0.10527586936950684
INFO 2025-02-26 19:34:00,872 operation "GET - AuthController[verify] /api/auth/verify" 0.0023069381713867188
INFO 2025-02-26 19:34:00,943 operation "GET - DraftController[get_drafts] /api/drafts/" 0.02136397361755371
INFO 2025-02-26 19:34:00,979 mtprotosender Connecting to 149.154.167.92:443/TcpFull...
INFO 2025-02-26 19:34:00,995 operation "GET - DraftController[get_drafts] /api/drafts/" 0.03175997734069824
INFO 2025-02-26 19:34:01,007 mtprotosender Connection to 149.154.167.92:443/TcpFull complete!
INFO 2025-02-26 19:34:01,036 operation "GET - TelegramController[get_channel_data] /api/tg/get_channel_data" 0.10963320732116699
INFO 2025-02-26 19:34:01,100 operation "GET - TelegramController[get_messages] /api/tg/messages" 0.174699068069458
INFO 2025-02-26 19:34:01,120 operation "GET - TelegramController[get_channel_data] /api/tg/get_channel_data" 0.07750415802001953
INFO 2025-02-26 19:34:01,192 operation "GET - TelegramController[get_messages] /api/tg/messages" 0.08819198608398438
INFO 2025-02-26 19:34:02,130 mtprotosender Disconnecting from 149.154.167.92:443/TcpFull...
INFO 2025-02-26 19:34:02,130 mtprotosender Disconnection from 149.154.167.92:443/TcpFull complete!
INFO 2025-02-26 19:34:02,161 operation "GET - TelegramController[refresh_data] /api/tg/refresh_data" 1.2333488464355469
INFO 2025-02-26 19:34:02,169 mtprotosender Connecting to 149.154.167.92:443/TcpFull...
INFO 2025-02-26 19:34:02,205 mtprotosender Connection to 149.154.167.92:443/TcpFull complete!
INFO 2025-02-26 19:34:03,894 mtprotosender Disconnecting from 149.154.167.92:443/TcpFull...
INFO 2025-02-26 19:34:03,894 mtprotosender Disconnection from 149.154.167.92:443/TcpFull complete!
INFO 2025-02-26 19:34:03,920 operation "GET - TelegramController[refresh_data] /api/tg/refresh_data" 1.7531709671020508
INFO 2025-02-26 19:34:09,325 operation "GET - AuthController[verify] /api/auth/verify" 0.018604755401611328
INFO 2025-02-26 19:34:09,355 operation "GET - AuthController[verify] /api/auth/verify" 0.025722980499267578
INFO 2025-02-26 19:34:09,391 operation "GET - DraftController[get_drafts] /api/drafts/" 0.016235828399658203
INFO 2025-02-26 19:34:09,401 mtprotosender Connecting to 149.154.167.92:443/TcpFull...
INFO 2025-02-26 19:34:09,404 operation "GET - TelegramController[get_channel_data] /api/tg/get_channel_data" 0.026129961013793945
INFO 2025-02-26 19:34:09,415 operation "GET - DraftController[get_drafts] /api/drafts/" 0.012937307357788086
INFO 2025-02-26 19:34:09,460 operation "GET - TelegramController[get_channel_data] /api/tg/get_channel_data" 0.051201820373535156
INFO 2025-02-26 19:34:09,482 mtprotosender Connection to 149.154.167.92:443/TcpFull complete!
INFO 2025-02-26 19:34:09,633 operation "GET - TelegramController[get_messages] /api/tg/messages" 0.2566189765930176
INFO 2025-02-26 19:34:09,908 operation "GET - TelegramController[get_messages] /api/tg/messages" 0.2669527530670166
INFO 2025-02-26 19:34:10,972 mtprotosender Disconnecting from 149.154.167.92:443/TcpFull...
INFO 2025-02-26 19:34:10,973 mtprotosender Disconnection from 149.154.167.92:443/TcpFull complete!
INFO 2025-02-26 19:34:11,000 operation "GET - TelegramController[refresh_data] /api/tg/refresh_data" 1.6180920600891113
INFO 2025-02-26 19:34:11,005 mtprotosender Connecting to 149.154.167.92:443/TcpFull...
INFO 2025-02-26 19:34:11,087 mtprotosender Connection to 149.154.167.92:443/TcpFull complete!
INFO 2025-02-26 19:34:12,499 mtprotosender Disconnecting from 149.154.167.92:443/TcpFull...
INFO 2025-02-26 19:34:12,499 mtprotosender Disconnection from 149.154.167.92:443/TcpFull complete!
INFO 2025-02-26 19:34:12,528 operation "GET - TelegramController[refresh_data] /api/tg/refresh_data" 1.5247468948364258
